### ISSUE TITLE
Feature requests for repocli

### ISSUE THREAD

**Issue by achetverikov** [Donders-Institute/tg-toolset-golang#1]
I used repocli to get files from SURFDrive to the project folder at DCCN, it works great. To improve it further a couple of things could be added:
1) a capability to synchronize folders without overwriting
2) the average download speed in the progress status 
3) a guesstimate on the completion time (currently only the number of files is shown which updates when folders are parsed recursively)
4) autocompletion of local and remote filenames
5) create and compare checksums

**Comment by hurngchunlee** [comment]
@achetverikov thanks for the feedback.

Concerning your request 1, since the WebDAV protocol doesn't provide checksum, it is not possible to implement a trusty synchronization.  The only thing we can rely on is based on size and the last modification time.  Shall we implement "without overwriting" dynamically based on those two factors, or shall we just provide a flag to toggle overwrite (and by default is not to overwrite)?  

Likewise, it is impossible to implement checksum check with the WebDAV interface, unfortunately.

**Comment by achetverikov** [comment]
I think a flag would be a simpler and more straightforward solution.

**Comment by hurngchunlee** [comment]
@achetverikov except the "checksum" comparison, other requests are implemented in [release 1.7.0](https://github.com/Donders-Institute/tg-toolset-golang/releases/tag/1.7.0)

I am closing this issue.
